version: "3"
services:
  app:
    build: .
    command: rails s -p 3000 -b "0.0.0.0"
    ports:
      - 3000:3000
    volumes:
      - .:/mblog
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
  db:
    image: mysql:5.7.29
    volumes:
      - ./tmp/db/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
