version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose up -d
      - run: sleep 15
      - run: docker-compose exec app rake db:setup
      - run: docker-compose exec app rspec

workflows:
  version: 2
  test:
    jobs:
      - test
