# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5058dd15ccbee63f37a735651b0c01285290678474ee445f4580daf930f322e7ce0c76d97213d4985297b044c7b165a9621b01e9b95a428495cfb9a14f740c4f

test:
  secret_key_base: 7b6ac90f2d1a0994910c4cc2e25898736dc799c84f01d3522a2a699b3caab070a7b64e273d3fd979f4d8fd04e4e0d18eaecd4271c70217e6ba56a8079fd5017f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
